services:
  time:
    command: uvx mcp-server-time --local-timezone America/New_York
    build: .

  memory:
    command: npx -y @modelcontextprotocol/server-memory
    environment:
      MEMORY_FILE_PATH: "${HOME}/.config/mcp/memory.json"

  fetch:
    command: uvx mcp-server-fetch
    build: .

  aws-docs:
    command: uvx awslabs.aws-documentation-mcp-server@latest
    build: .
    labels:
      mcp.profile: work, aws, development

  github:
    image: ghcr.io/github/github-mcp-server
    environment:
      GITHUB_PERSONAL_ACCESS_TOKEN: ${GITHUB_PERSONAL_ACCESS_TOKEN}
    labels:
      mcp.profile: development

  postgres:
    command: uvx --from mcp-alchemy==2025.04.16.110003 --with psycopg2-binary --refresh-package mcp-alchemy mcp-alchemy
    environment:
      DB_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/postgres"
    labels:
      mcp.profile: postgres
    build: .

  applescript-mcp-server:
    command: node ${HOME}/code/applescript-mcp/dist/index.js
    labels:
      mcp.profile: productivity
    build: .

  obsidian:
    command: uvx mcp-obsidian ${HOME}/${OBSIDIAN_NOTES_PATH}
    environment:
      OBSIDIAN_API_KEY: ${OBSIDIAN_API_KEY}
    labels:
      mcp.profile: work, productivity, research, search
    build: .

  brave:
    image: mcp/brave-search
    environment:
      BRAVE_API_KEY: ${BRAVE_API_KEY}
    labels:
      mcp.profile: default, development, research, search

  neo4j:
    command: uvx mcp-neo4j-cypher@0.2.1
    environment:
      NEO4J_URI: bolt://localhost:7687
      NEO4J_DATABASE: ${NEO4J_DATABASE} 
      NEO4J_USERNAME: ${NEO4J_USERNAME}
      NEO4J_PASSWORD: ${NEO4J_PASSWORD}
    labels:
      mcp.profile: graph

  cloudwatch:
    command: uv --directory ${HOME}/code/Log-Analyzer-with-MCP/src/cw-mcp-server run server.py
    labels:
      mcp.profile: aws

  amazon-mcp:
    command: amzn-mcp
    environment:
      QUIP_API_TOKEN: ${QUIP_API_TOKEN}
    labels:
      mcp.profile: work, aws, quip, productivity

  terraform:
    command: uvx awslabs.terraform-mcp-server@latest
    labels:
      mcp.profile: development, aws, terraform
